#!/usr/bin/env python3
"""Check the two claims in AA's 2026-07-21 reply about Appendix F.

Claim 1 (Table 36 p-values): AA says he "always used a standard two-sided
proportion t-test" and now gets Greedy 0.137, Need 0.536, Theft 0.0288
(vs 0.13 / 0.42 / 0.015 hardcoded in main.tex, which he too cannot
reproduce). Hypothesis from the verify_hp_moral_tables battery: AA's test
is the two-sided test of equal proportions WITH continuity correction
(R's prop.test default = Yates-corrected chi2). This script recomputes the
full menu of two-sample proportion tests on the exact T36 counts and flags
which test rounds to AA's three numbers and which to the published ones.
It also checks that every "<0.001" entry of Tables 35/36 survives under
the Yates-corrected test, so the whole p-value column can be attributed
to one named test.

Claim 2 (Tables 32/37 rep/beh splits): AA says the decomposition is over
social proximity "HighSP vs LowSP". The earlier sweeps tested the SP-5,
moral-7 and joint cells; here the BINARY High/Low SP split is decomposed
at every cutoff (sp_num >= 1,2,3,4; the paper's High SP = sp_num >= 2),
under the symmetrized, both one-sided (Oaxaca), and pooled-reference
variants, for all six outcomes of Tables 32 and 37. If none reproduces
the hardcoded rep/beh columns on this retained-text sample, AA's answer
is compatible with the shipped file only via the all-four-texts
hypothesis (per-level file already requested from AA on 2026-07-21).

Output: output/tables/aa_reply_checks.txt

RESOLVED 2026-07-21 (later the same day): AA recovered his code and
confirmed the published Table 32/37 splits came from an erroneous
all-observations run; he endorsed recomputing on the hpmin sample. The
tables are now generated by code/23_hp_decomposition_tables.py and verified
in verify_hp_moral_tables.py; the per-level delivery is checked in
aa_perlevel_checks.py. This script remains as the record of the Claim 1
identification (chi2-Yates) and the Claim 2 refutation on the retained-text
sample.
"""

from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from verify_hp_moral_tables import (onesided_decompose, outcome_series,
                                    sym_decompose)

HERE = Path(__file__).resolve().parent
PKG = HERE.parent.parent
DATA = PKG / "data"
TABLES = PKG / "output" / "tables"

L: list[str] = []


def log(*s: object) -> None:
    L.append(" ".join(str(x) for x in s))
    print(L[-1])


def rounds_to(p: float, target: str) -> bool:
    dp = len(target.split(".")[1])
    return abs(p - float(target)) <= 0.5 * 10 ** (-dp) + 1e-12


def prop_test_menu(x1: int, n1: int, x2: int, n2: int) -> dict[str, float]:
    table = np.array([[x1, n1 - x1], [x2, n2 - x2]])
    p1, p2 = x1 / n1, x2 / n2
    pp = (x1 + x2) / (n1 + n2)
    z_pooled = (p1 - p2) / np.sqrt(pp * (1 - pp) * (1 / n1 + 1 / n2))
    z_unpooled = (p1 - p2) / np.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)
    b1 = np.repeat([1.0, 0.0], [x1, n1 - x1])
    b2 = np.repeat([1.0, 0.0], [x2, n2 - x2])
    return {
        "z pooled (= chi2)": 2 * stats.norm.sf(abs(z_pooled)),
        "z unpooled": 2 * stats.norm.sf(abs(z_unpooled)),
        "t Student (binary)": stats.ttest_ind(b1, b2, equal_var=True).pvalue,
        "t Welch (binary)": stats.ttest_ind(b1, b2, equal_var=False).pvalue,
        "chi2-Yates (prop.test)": stats.chi2_contingency(
            table, correction=True).pvalue,
        "G": stats.chi2_contingency(table, correction=False,
                                    lambda_="log-likelihood").pvalue,
        "Fisher": stats.fisher_exact(table)[1],
        "Barnard": stats.barnard_exact(table).pvalue,
    }


def decompose_binary(d: pd.DataFrame, groupcol: str, g_hi, g_lo,
                     expected: dict[str, tuple[float, float, float]],
                     title: str) -> None:
    log(f"\n=== {title} ===")
    for cut in (1, 2, 3, 4):
        dd = d.assign(hsp=(d.sp_num >= cut).map({True: "High", False: "Low"}))
        log(f"\n  cutoff High SP = sp_num >= {cut}"
            + ("   <-- the paper's High SP definition" if cut == 2 else ""))
        any_match = False
        for name, y in outcome_series(dd).items():
            ddy = dd.assign(_y=y)
            want = expected[name]
            diff, repS, behS = sym_decompose(ddy, "hsp", groupcol,
                                             g_hi, g_lo, "_y")
            (rA, bA), (rB, bB) = onesided_decompose(ddy, "hsp", groupcol,
                                                    g_hi, g_lo, "_y")
            hi = ddy[ddy[groupcol] == g_hi]
            lo = ddy[ddy[groupcol] == g_lo]
            qH = hi.hsp.value_counts(normalize=True)
            qL = lo.hsp.value_counts(normalize=True)
            yP = ddy.groupby("hsp")._y.mean()
            repP = sum((qH.get(c, 0.0) - qL.get(c, 0.0)) * yP[c]
                       for c in yP.index)
            variants = {"sym": (repS, behS), "one-sided A": (rA, bA),
                        "one-sided B": (rB, bB),
                        "pooled-ref": (repP, diff - repP)}
            hits = [k for k, (r, b) in variants.items()
                    if abs(r - want[1]) <= 5e-4 and abs(b - want[2]) <= 5e-4]
            any_match = any_match or bool(hits)
            log(f"    {name:15s} hardcoded rep/beh {want[1]:+.3f}/{want[2]:+.3f}"
                f" | sym {repS:+.4f}/{behS:+.4f} A {rA:+.4f}/{bA:+.4f}"
                f" B {rB:+.4f}/{bB:+.4f} P {repP:+.4f}/{diff - repP:+.4f}"
                + (f"  MATCH {hits}" if hits else ""))
        y = outcome_series(dd)["Mean Allocation"]
        ddy = dd.assign(_y=y)
        diff, repS, _ = sym_decompose(ddy, "hsp", groupcol, g_hi, g_lo, "_y")
        log(f"    mean-allocation rep share of gap: sym {repS / diff:.1%}"
            f" vs hardcoded "
            f"{expected['Mean Allocation'][1] / expected['Mean Allocation'][0]:.1%}")
        if not any_match:
            log("    -> NO variant reproduces any hardcoded split at this cutoff")


def main() -> None:
    d = pd.read_excel(DATA / "hpmin_sp_moral_all.xlsx")
    ctl = d[d.Market == 0]
    mkt = d[d.Market == 1]

    # --- Claim 1: Table 36 p-values -------------------------------------
    log("=== Claim 1: Table 36 p-values (Market N=%d vs Control N=%d) ==="
        % (len(mkt), len(ctl)))
    aa_says = {"Greedy": "0.137", "Need": "0.536", "Theft": "0.0288"}
    paper = {"Greedy": "0.13", "Need": "0.42", "Theft": "0.015"}
    for lvl, aa_p in aa_says.items():
        x1, x2 = (mkt.moral == lvl).sum(), (ctl.moral == lvl).sum()
        menu = prop_test_menu(x1, len(mkt), x2, len(ctl))
        log(f"\n  {lvl}: Market {x1}/{len(mkt)} vs Control {x2}/{len(ctl)}"
            f"  (AA now gets {aa_p}; paper has {paper[lvl]})")
        for k, v in menu.items():
            tags = []
            if rounds_to(v, aa_p):
                tags.append("= AA")
            if rounds_to(v, paper[lvl]):
                tags.append("= paper")
            log(f"    {k:24s} {v:.4f}" + ("   <-- " + ", ".join(tags)
                                          if tags else ""))
    log("\n  All '<0.001' rows of Tables 35/36 under chi2-Yates (prop.test):")
    for col, lvls in [("social_proximity",
                       ["No mention of recipient", "Abstract stranger",
                        "Anonymous peer", "Teammate / coworker", "Friend"]),
                      ("moral", ["Egalitarian", "Entitlement", "Generous",
                                 "Neutral"])]:
        for lvl in lvls:
            x1, x2 = (mkt[col] == lvl).sum(), (ctl[col] == lvl).sum()
            p = stats.chi2_contingency(
                np.array([[x1, len(mkt) - x1], [x2, len(ctl) - x2]]),
                correction=True).pvalue
            log(f"    {col:17s} {lvl:24s} p = {p:.2e}  "
                + ("OK <0.001" if p < 0.001 else "NOT <0.001"))

    # --- Claim 2: binary High/Low SP decompositions ---------------------
    expected37 = {"Mean Allocation": (-1.996, -1.132, -0.864),
                  "=4": (0.025, 0.012, 0.013),
                  "=6": (0.416, 0.221, 0.195),
                  "=8": (0.027, 0.021, 0.006),
                  ">8": (-0.461, -0.262, -0.200),
                  "=12": (-0.150, -0.076, -0.074)}
    decompose_binary(d, "Market", 0, 1, expected37,
                     "Claim 2a: Table 37 (Control - Market), binary High/Low SP")
    expected32 = {"Mean Allocation": (0.998, 0.491, 0.506),
                  "=4": (-0.065, -0.032, -0.033),
                  "=6": (-0.035, -0.019, -0.016),
                  "=8": (-0.075, -0.036, -0.039),
                  ">8": (0.205, 0.102, 0.103),
                  "=12": (0.105, 0.051, 0.054)}
    decompose_binary(ctl, "treatment", "kw", "lt", expected32,
                     "Claim 2b: Table 32 (KW - LT, Control), binary High/Low SP")

    out = TABLES / "aa_reply_checks.txt"
    out.write_text("\n".join(L) + "\n")
    log(f"\nwritten: {out}")


if __name__ == "__main__":
    main()
