#!/usr/bin/env python3
"""Back the hardcoded Appendix F social-proximity tables with a computed log
(2026-07-20 Numbers-Reviewer follow-up). The tables were pasted into main.tex
with no generating script in the package; this script recomputes them from
data/hpmin_social_proximity_all.xlsx and PASS/FAILs each hardcoded cell.

Covered: tab:decomposition_sym_kw_lt (Table 32), tab:freqs_market_control_sp
(Table 35), tab:decomposition_sym_pooled_m0m1 (Table 37).
UPDATE 2026-07-21: AA delivered the moral-scheme classification as
data/hpmin_sp_moral_all.xlsx; verify_hp_moral_tables.py now verifies ALL App F
exhibits from it. RESOLVED later the same day: AA recovered his code and
confirmed the published rep/beh splits of Tables 32/37 came from an erroneous
all-observations run (all four hp texts per participant); the tables are now
GENERATED on the hpmin sample by code/23_hp_decomposition_tables.py (SP-5
cells, symmetrized) and fully verified in verify_hp_moral_tables.py. The
expected32/expected37 splits below are the RETIRED published values, kept as
the record of what this script diagnosed; only the observed-diff column is
graded here.

Outputs: output/tables/verify_hp_appendix_stats.txt
"""

from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

HERE = Path(__file__).resolve().parent
PKG = HERE.parent.parent
DATA = PKG / "data"
TABLES = PKG / "output" / "tables"

SP_LEVELS = ["No mention of recipient", "Abstract stranger", "Anonymous peer",
             "Teammate / coworker", "Friend"]

L: list[str] = []
n_fail = 0


def log(*s: object) -> None:
    L.append(" ".join(str(x) for x in s))
    print(L[-1])


def ok(name: str, cond: bool) -> None:
    global n_fail
    log(("  PASS  " if cond else "  FAIL  ") + name)
    n_fail += 0 if cond else 1


def sym_decompose(d: pd.DataFrame, groupcol: str, g_hi, g_lo, ycol: str) -> tuple[float, float, float]:
    """Symmetrized (Shapley) two-way decomposition of E[y|hi]-E[y|lo] over SP cells."""
    hi, lo = d[d[groupcol] == g_hi], d[d[groupcol] == g_lo]
    qH = hi.social_proximity.value_counts(normalize=True)
    qL = lo.social_proximity.value_counts(normalize=True)
    yH = hi.groupby("social_proximity")[ycol].mean()
    yL = lo.groupby("social_proximity")[ycol].mean()
    diff = hi[ycol].mean() - lo[ycol].mean()
    rep = beh = 0.0
    for c in sorted(set(qH.index) | set(qL.index)):
        qh, ql = qH.get(c, 0.0), qL.get(c, 0.0)
        yh, yl = yH.get(c, np.nan), yL.get(c, np.nan)
        rep += (qh - ql) * np.nanmean([yh, yl])
        if np.isfinite(yh) and np.isfinite(yl):
            beh += (qh + ql) / 2 * (yh - yl)
    return diff, rep, beh


def check_rows(d: pd.DataFrame, groupcol: str, g_hi, g_lo, expected: dict, title: str) -> None:
    """Verify the Observed Diff column (computable from shipped data). The
    published representation/behavior splits graded nowhere here were RETIRED
    on 2026-07-21 (erroneous all-observations construction, per AA); the
    paper's tables are now generated by 23_hp_decomposition_tables.py and the
    SP-5 splits logged below are the ones the paper displays."""
    log(f"\n--- {title} ---")
    d = d.copy()
    d["high_sp"] = d.sp_num >= 2
    outcomes = {
        "Mean Allocation": d.allocation,
        "Allocation = 4": (d.allocation == 4).astype(float),
        "Allocation = 6": (d.allocation == 6).astype(float),
        "Allocation = 8": (d.allocation == 8).astype(float),
        "Allocation > 8": (d.allocation > 8).astype(float),
        "Allocation = 12": (d.allocation == 12).astype(float),
    }
    for name, y in outcomes.items():
        dd = d.assign(_y=y)
        diff, rep5, beh5 = sym_decompose(dd, groupcol, g_hi, g_lo, "_y")
        _, rep2, beh2 = sym_decompose(dd.assign(social_proximity=dd.high_sp), groupcol, g_hi, g_lo, "_y")
        want = expected[name]
        ok(f"{name}: observed diff {diff:+.3f} vs hardcoded {want[0]:+.3f}",
           abs(diff - want[0]) < 0.0015)
        log(f"      retired published split rep/beh {want[1]:+.3f}/{want[2]:+.3f}; SP-5 cells give "
            f"{rep5:+.3f}/{beh5:+.3f} (the paper's generated table), binary high-SP "
            f"gives {rep2:+.3f}/{beh2:+.3f}")


def main() -> None:
    d = pd.read_excel(DATA / "hpmin_social_proximity_all.xlsx")
    assert len(d) == 1200 and set(d.social_proximity.unique()) == set(SP_LEVELS)
    log(f"hpmin_social_proximity_all.xlsx: N={len(d)}, "
        f"cells kw/lt x Market0/1 = {d.groupby(['treatment', 'Market']).size().tolist()}")

    # --- Table 35: SP distribution, Market vs Control (both games pooled) ---
    log("\n--- tab:freqs_market_control_sp (Table 35) ---")
    expected35 = {"No mention of recipient": (75.88, 28.75), "Abstract stranger": (10.75, 28.25),
                  "Anonymous peer": (5.00, 18.25), "Teammate / coworker": (2.13, 6.50),
                  "Friend": (6.25, 18.25)}
    mkt, ctl = d[d.Market == 1], d[d.Market == 0]
    for lvl, (wm, wc) in expected35.items():
        gm = 100 * (mkt.social_proximity == lvl).mean()
        gc = 100 * (ctl.social_proximity == lvl).mean()
        cnt = np.array([(mkt.social_proximity == lvl).sum(), (ctl.social_proximity == lvl).sum()])
        tot = np.array([len(mkt), len(ctl)])
        chi2 = stats.chi2_contingency(np.array([cnt, tot - cnt]).T, correction=False)
        ok(f"{lvl}: Market {gm:.4f} / Control {gc:.4f} vs hardcoded {wm} / {wc}; "
           f"p={chi2.pvalue:.2e} (<0.001: {chi2.pvalue < 0.001})",
           abs(gm - wm) <= 0.005 and abs(gc - wc) <= 0.005 and chi2.pvalue < 0.001)

    # --- Table 32: KW - LT symmetrized decomposition, Control condition ---
    expected32 = {"Mean Allocation": (0.998, 0.491, 0.506),
                  "Allocation = 4": (-0.065, -0.032, -0.033),
                  "Allocation = 6": (-0.035, -0.019, -0.016),
                  "Allocation = 8": (-0.075, -0.036, -0.039),
                  "Allocation > 8": (0.205, 0.102, 0.103),
                  "Allocation = 12": (0.105, 0.051, 0.054)}
    check_rows(d[d.Market == 0], "treatment", "kw", "lt", expected32,
               "tab:decomposition_sym_kw_lt (Table 32): KW - LT, Control")

    # --- Table 37: Control - Market symmetrized decomposition, both games pooled ---
    expected37 = {"Mean Allocation": (-1.996, -1.132, -0.864),
                  "Allocation = 4": (0.025, 0.012, 0.013),
                  "Allocation = 6": (0.416, 0.221, 0.195),
                  "Allocation = 8": (0.027, 0.021, 0.006),
                  "Allocation > 8": (-0.461, -0.262, -0.200),
                  "Allocation = 12": (-0.150, -0.076, -0.074)}
    check_rows(d, "Market", 0, 1, expected37,
               "tab:decomposition_sym_pooled_m0m1 (Table 37): Control - Market, pooled")

    log("\nTables 33/34/36 (moral scheme) are covered by verify_hp_moral_tables.py "
        "from data/hpmin_sp_moral_all.xlsx (AA, 2026-07-21); Tables 32/37 are "
        "generated by 23_hp_decomposition_tables.py and fully verified there "
        "(the published splits were retired as an erroneous all-observations "
        "construction, see aa_perlevel_checks.py).")
    (TABLES / "verify_hp_appendix_stats.txt").write_text("\n".join(L) + "\n")
    print(f"\n{'ALL CHECKS PASS' if n_fail == 0 else f'{n_fail} CHECK(S) FAILED'}"
          f" — wrote {TABLES / 'verify_hp_appendix_stats.txt'}")


if __name__ == "__main__":
    main()
